// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-bikes.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
import { bikeProducts } from "npm:@/data/products";
var list_bikes_default = defineTool({
  name: "list_bikes",
  title: "List e-bikes",
  description: "List the WJ Vision e-bike catalog with prices, categories, and specs. Optionally filter by category.",
  inputSchema: {
    category: z.enum(["city", "commuter", "sport", "cargo"]).optional().describe("Optional bike category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const bikes = category ? bikeProducts.filter((b) => b.category === category) : bikeProducts;
    const rows = bikes.map((b) => ({
      id: b.id,
      name: b.name,
      tagline: b.tagline,
      category: b.category,
      price_eur: b.price,
      original_price_eur: b.originalPrice,
      specs: b.specs,
      features: b.features,
      colors: b.colors.map((c) => c.name),
      is_new: !!b.isNew,
      is_bestseller: !!b.isBestseller
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { bikes: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/get-bike.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { bikeProducts as bikeProducts2 } from "npm:@/data/products";
var get_bike_default = defineTool2({
  name: "get_bike",
  title: "Get bike details",
  description: "Get full details for a specific WJ Vision e-bike by its id (e.g. 'vision-x1').",
  inputSchema: {
    id: z2.string().min(1).describe("The bike id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const bike = bikeProducts2.find((b) => b.id === id);
    if (!bike) {
      return {
        content: [{ type: "text", text: `No bike found with id "${id}".` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(bike, null, 2) }],
      structuredContent: { bike }
    };
  }
});

// src/lib/mcp/tools/list-accessories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { accessories } from "npm:@/data/accessories";
var list_accessories_default = defineTool3({
  name: "list_accessories",
  title: "List accessories",
  description: "List WJ Vision accessories (helmets, locks, bags, tech, etc.). Optionally filter by category.",
  inputSchema: {
    category: z3.enum(["safety", "storage", "tech", "comfort", "protection"]).optional().describe("Optional accessory category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const items = category ? accessories.filter((a) => a.category === category) : accessories;
    const rows = items.map((a) => ({
      id: a.id,
      name: a.name,
      tagline: a.tagline,
      category: a.category,
      price_eur: a.price,
      original_price_eur: a.originalPrice,
      specs: a.specs,
      features: a.features,
      is_new: !!a.isNew,
      is_bestseller: !!a.isBestseller
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { accessories: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "wj-vision-mcp",
  title: "WJ Vision E-Bikes",
  version: "0.1.0",
  instructions: "Tools for browsing the WJ Vision e-bike and accessory catalog. Use `list_bikes` to browse bikes (optionally by category), `get_bike` for full specs of one bike by id, and `list_accessories` to browse accessories.",
  tools: [list_bikes_default, get_bike_default, list_accessories_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
